services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: condoririSG
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./writable:/var/www/html/writable
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - condoriri-network

networks:
  condoriri-network:
    external: true