services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: condoririSG
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./writable:/var/www/html/writable
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: >
      bash -c "chown -R www-data:www-data /var/www/html/writable &&
               chmod -R 755 /var/www/html/writable &&
               apache2-foreground"
    networks:
      - condoriri-network

networks:
  condoriri-network:
    external: true